import { useEffect, useMemo, useState } from 'react';
import { Clock3, X } from 'lucide-react';
import type { Cliente, Hora, Servicio } from '../types';

export function QuickHourLog({ clientes, servicios, horas, onSave }: { clientes: Cliente[]; servicios: Servicio[]; horas: Hora[]; onSave: (hours: Hora[]) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [fecha, setFecha] = useState(() => new Date().toISOString().slice(0, 10));
  const [inicio, setInicio] = useState('09:00'); const [fin, setFin] = useState('10:00');
  const [clienteId, setClienteId] = useState(''); const [servicioId, setServicioId] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!clienteId && clientes[0]) setClienteId(clientes.find((c) => c.activo)?.id || clientes[0].id); }, [clientes, clienteId]);
  useEffect(() => { if (!servicioId && servicios[0]) setServicioId(servicios[0].id); }, [servicios, servicioId]);
  const total = useMemo(() => Math.max(0, (new Date(`${fecha}T${fin}:00`).getTime() - new Date(`${fecha}T${inicio}:00`).getTime()) / 3_600_000), [fecha, inicio, fin]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!clienteId || !servicioId || total <= 0) return; setSaving(true); try { const cliente = clientes.find((c) => c.id === clienteId); const servicio = servicios.find((s) => s.id === servicioId); await onSave([{ id: `ho_${Date.now().toString().slice(-6)}`, fecha, cliente_id: clienteId, cliente_nombre: cliente?.nombre || 'Cliente', servicio_id: servicioId, servicio_nombre: servicio?.nombre || 'Servicio', horas: total, descripcion: `Registro rápido ${inicio}–${fin}` }, ...horas]); setOpen(false); } finally { setSaving(false); } };
  return <><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 shadow-sm hover:bg-slate-50"><Clock3 className="h-4 w-4 text-blue-600" /><span className="hidden sm:inline">Registrar horas</span></button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">Registro rápido de horas</h2><p className="text-xs text-slate-500">El total se calcula con inicio y finalización.</p></div><button type="button" onClick={() => setOpen(false)} className="text-slate-500"><X className="h-5 w-5" /></button></div><div className="grid grid-cols-2 gap-3 text-xs"><label>Fecha<input required type="date" value={fecha} onChange={(e) => setFecha(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label>Cliente<select required value={clienteId} onChange={(e) => setClienteId(e.target.value)} className="mt-1 w-full rounded-lg border p-2">{clientes.map((c) => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Inicio<input required type="time" value={inicio} onChange={(e) => setInicio(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label>Fin<input required type="time" value={fin} onChange={(e) => setFin(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="col-span-2">Servicio<select required value={servicioId} onChange={(e) => setServicioId(e.target.value)} className="mt-1 w-full rounded-lg border p-2">{servicios.map((s) => <option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label></div><p className="mt-3 text-sm font-semibold text-slate-800">Total: {total.toFixed(2)} h</p><button disabled={saving || total <= 0 || !clienteId || !servicioId} className="mt-4 w-full rounded-xl bg-blue-700 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Guardando…' : 'Guardar horas'}</button></form></div>}</>;
}
