import type { AppData } from "../../src/types";
export const fixture: AppData = {
  config: {
    trm: 4000,
    uvt: 47065,
    smmlv: 1423500,
    tope_no_declarante_uvt: 1400,
    tope_no_paga_renta_uvt: 1090,
    tope_responsable_iva_uvt: 3500,
    retencion_servicio_min_uvt: 4,
    tarifa_ret_declarante: 0.04,
    tarifa_ret_no_declarante: 0.06,
    tarifa_salud: 0.125,
    tarifa_pension: 0.16,
    ibc_porcentaje: 0.4,
    tarifa_iva: 0.19,
    salario_propuesto: 3000000,
    horas_objetivo_mes: 160,
    meta_ventas_mensual: 15000000,
    margen_minimo: 0.3,
    umbral_perdida_horas: 0.75,
  },
  clientes: [
    {
      id: "demo-norte",
      nombre: "Estudio Norte",
      tipo: "Nacional",
      declarante: true,
      activo: true,
      fecha_creacion: "2026-08-01",
      progreso: 65,
      responsable: "Equipo creativo",
      marca_info: "Identidad y estrategia de marca",
      objetivos: JSON.stringify([
        {
          id: "o1",
          text: "Entregar la identidad visual",
          metaFecha: "2026-10-30",
          completado: false,
        },
      ]),
      entregables: JSON.stringify([
        { id: "e1", nombre: "Dirección visual", estado: "Cumplido", fecha: "2026-10-05" },
        { id: "e2", nombre: "Manual de marca", estado: "En Progreso", fecha: "2026-10-25" },
      ]),
    },
    {
      id: "demo-oliva",
      nombre: "Casa Oliva",
      tipo: "Nacional",
      declarante: true,
      activo: true,
      fecha_creacion: "2026-08-10",
      progreso: 40,
      responsable: "Equipo creativo",
    },
    {
      id: "demo-luma",
      nombre: "Luma Studio",
      tipo: "Internacional",
      declarante: false,
      activo: true,
      fecha_creacion: "2026-09-01",
      progreso: 80,
    },
  ],
  servicios: [
    {
      id: "s1",
      nombre: "Identidad de marca",
      tipo: "servicio",
      costo_unitario: 900000,
      costo_entrega_estimado: 900000,
      precio_habitual: 4200000,
      precio_habitual_moneda: "COP",
      margen_objetivo: 0.35,
      aplica_iva: false,
    },
    {
      id: "s2",
      nombre: "Estrategia digital",
      tipo: "servicio",
      costo_unitario: 600000,
      precio_habitual: 3000000,
      precio_habitual_moneda: "COP",
      aplica_iva: false,
    },
  ],
  ventas: [
    {
      id: "v1",
      fecha: "2026-10-02",
      cliente_id: "demo-norte",
      cliente_nombre: "Estudio Norte",
      servicio_id: "s1",
      servicio_nombre: "Identidad de marca",
      cantidad: 1,
      precio_venta_unitario: 4200000,
      costo_unitario: 900000,
      moneda: "COP",
      tipo: "Nacional",
      adelanto: 3300000,
      estado_pago: "Adelanto",
    },
    {
      id: "v2",
      fecha: "2026-10-04",
      cliente_id: "demo-oliva",
      cliente_nombre: "Casa Oliva",
      servicio_id: "s2",
      servicio_nombre: "Estrategia digital",
      cantidad: 1,
      precio_venta_unitario: 3000000,
      costo_unitario: 600000,
      moneda: "COP",
      tipo: "Nacional",
      adelanto: 1800000,
      estado_pago: "Adelanto",
    },
    {
      id: "v3",
      fecha: "2026-10-07",
      cliente_id: "demo-luma",
      cliente_nombre: "Luma Studio",
      servicio_id: "s2",
      servicio_nombre: "Estrategia digital",
      cantidad: 1,
      precio_venta_unitario: 300,
      costo_unitario: 240000,
      moneda: "USD",
      tipo: "Internacional",
      adelanto: 300,
      estado_pago: "Pagado",
    },
  ],
  horas: [
    {
      id: "h1",
      fecha: "2026-10-03",
      cliente_id: "demo-norte",
      cliente_nombre: "Estudio Norte",
      servicio_id: "s1",
      servicio_nombre: "Identidad de marca",
      horas: 32,
      descripcion: "Diseño y dirección",
    },
    {
      id: "h2",
      fecha: "2026-10-06",
      cliente_id: "demo-oliva",
      cliente_nombre: "Casa Oliva",
      servicio_id: "s2",
      servicio_nombre: "Estrategia digital",
      horas: 20,
      descripcion: "Planificación",
    },
    {
      id: "h3",
      fecha: "2026-10-07",
      cliente_id: "demo-luma",
      cliente_nombre: "Luma Studio",
      servicio_id: "s2",
      servicio_nombre: "Estrategia digital",
      horas: 12,
      descripcion: "Seguimiento",
    },
  ],
  herramientas: [
    {
      id: "t1",
      nombre: "Software de diseño",
      monto: 180000,
      moneda: "COP",
      tipo_cobro: "global",
      servicios_ids: "s1,s2",
    },
  ],
  otrosGastos: [
    {
      id: "g1",
      nombre: "Operación del estudio",
      monto: 320000,
      moneda: "COP",
      categoria: "Operativo",
    },
  ],
  pagosEgresos: [],
  respaldos: [],
};



// Historical sample sales make the existing trend chart representative; October KPIs retain their own period.
[2500000, 3300000, 4800000, 6100000, 7200000].forEach((amount, index) => {
  fixture.ventas.push({
    ...fixture.ventas[0], id: `historical-${index}`, fecha: `2026-${String(index + 5).padStart(2, '0')}-15`,
    precio_venta_unitario: amount, adelanto: amount, estado_pago: 'Pagado',
  });
});
