-- Fase 1 (seguridad) — Ferova One: elimina la columna access_token muerta de
-- google_workspace_connections.
--
-- Contexto: desde el harden 20260718123000 esta columna quedó SIEMPRE en NULL.
-- Ninguna edge function la escribe (verificado en todo supabase/functions), el
-- navegador nunca la lee (grant a `authenticated` revocado), y el token real de
-- Google vive solo en session.provider_token (memoria del navegador), que se
-- reenvía en el cuerpo de cada petición y nunca se persiste.
--
-- Al eliminar la columna: ni un volcado de la BD ni una fuga de la clave
-- service_role pueden revelar un token OAuth (no hay ninguno en reposo), y
-- ningún desarrollo futuro puede repoblarla por accidente. Es idempotente.
ALTER TABLE public.google_workspace_connections DROP COLUMN IF EXISTS access_token;
